project_name: goinit
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
builds:
  - main: .
    ldflags:
      - -s -w
      - -X github.com/mmmommm/goinit/cmd.Version={{.Version}}
      - -X github.com/mmmommm/goinit/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: goinit
    github:
      owner: mmmommm
      name: homebrew-tap
    url_template: "https://github.com/mmmommm/goinit/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: "https://mmmommm.github.io/"
    description: "Initialization for Go."
    test: |
      system "#{bin}/goinit -h"
    install: |
      bin.install "goinit"
