run:
  timeout: 10m
  skip-files: []
  skip-dirs: []

linters-settings:
  misspell:
    locale: US
  unused:
    go: "1.17"


linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - forcetypeassert
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ifshort
    - makezero
    - misspell
    - nilerr
    - noctx
    - revive
    - staticcheck
    - varcheck

issues:
  exclude-use-default: true
  max-per-linter: 0
  max-same-issues: 0
  exclude: []
